### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by arkilis** [HaloOrangeWang/NoiseMaker#3]
(.env) ➜  code git:(master) python3 main.py --outputpath=../output/1.mid
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from interfaces.midi.midi import multi_pianoroll_to_midi, midi2wav
  File "/Volumes/Apple/ben_ws/python_dev/AIMusic/NoiseMaker/code/interfaces/midi/midi.py", line 2, in <module>
    from interfaces.utils import min_number_except_1
  File "/Volumes/Apple/ben_ws/python_dev/AIMusic/NoiseMaker/code/interfaces/utils.py", line 201, in <module>
    DiaryLog = logger(diary_id=SystemArgs.diaryId)  # 日志输出
  File "/Volumes/Apple/ben_ws/python_dev/AIMusic/NoiseMaker/code/interfaces/utils.py", line 179, in logger
    fh = logging.FileHandler(filename=diary_path)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Apple/ben_ws/python_dev/AIMusic/NoiseMaker/Diary/Train/181115-0001.txt'

找不到该文件

**Comment by HaloOrangeWang** [comment]
在首次运行程序之前，需要新建几个程序日志的对应文件夹
$ mkdir Diary
$ mkdir Diary/Generate
$ mkdir Diary/Train
$ mkdir TrainData
$ mkdir TrainData/TfLog
$ mkdir TrainData/TfLog/sess

输入这些系统命令之后再运行程序，应该就不会出现这个错误了

**Comment by arkilis** [comment]
Worked!
